applog:
  level: "INFO"
  mod_level:
    sqlalchemy: "WARN"
    comtypes: "ERROR"
username: "A123456789"
password: "xxxxxxxxxx"
marketboard:
  subscription:
    tick: ["TX00"]
sqlalchemy:
  host: "splite://"
  echo: false
